// /api/artifacts - Agent deliverables and outputs
// GET: List artifacts by agent
// POST: Create new artifact

const fs = require('fs').promises;
const path = require('path');

// In-memory artifact storage
let artifacts = [];

// Sample artifacts that would be generated by agents
const SAMPLE_ARTIFACTS = [
  {
    id: 'art_1',
    agentId: 'marie_curie',
    type: 'research_report',
    title: 'AI Agent Market Analysis Q1 2026',
    summary: 'Analysis of 15 AI agent startups, market sizing, and competitive landscape',
    content: '## Key Findings\n\n1. Market size: $4.2B in 2026\n2. Top players: OpenAI, Anthropic, Cohere\n3. Emerging trend: Autonomous coding agents\n\n## Recommendations\n\n- Focus on vertical-specific agents\n- Build for enterprise security requirements\n- Differentiate on execution speed',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'completed'
  },
  {
    id: 'art_2',
    agentId: 'shakespeare',
    type: 'linkedin_post',
    title: 'Zero to One: The Real Story',
    summary: 'Draft post about execution vs ideas',
    content: 'I\'ve shipped 100+ projects. Here\'s what nobody tells you about zero to one:\n\n// The Myth\n\nEveryone thinks the idea is the hard part.\n\nIt\'s not.\n\n// The Reality\n\nAfter 5+ years of building:\n\n1. Ideas are cheap. Execution is everything.\n2. Speed beats perfection. Every time.\n3. The best founders ship ugly v1s.\n\n// The Bottom Line\n\nStop planning. Start shipping.\n\nWhat\'s something you\'ve been overthinking?',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    status: 'draft'
  },
  {
    id: 'art_3',
    agentId: 'jobs',
    type: 'lead_analysis',
    title: 'Grindery - Lead Analysis',
    summary: 'Deep dive on Grindery as potential client',
    content: '## Company Overview\n- Web3 Gateway for Zapier integration\n- Seed stage, EU-based\n- Team of 8\n\n## Fit Score: 8/10\n\n**Why good fit:**\n- Clear need for dev resources\n- Web3 + SaaS hybrid (our sweet spot)\n- Funded, can pay\n\n**Concerns:**\n- Small team, may not have budget\n- EU timezone difference\n\n## Recommended Approach\nPosition as integration specialist. Lead with portfolio of similar work.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    status: 'completed'
  },
  {
    id: 'art_4',
    agentId: 'nightingale',
    type: 'email_draft',
    title: 'Follow-up email to Soulverse',
    summary: 'Client check-in after project delivery',
    content: 'Subject: Checking in on Soul Super Wallet\n\nHi Team,\n\nHope the wallet launch went well! Wanted to check in and see how things are going post-launch.\n\nA few things I\'d love to hear about:\n- User feedback on the new UX\n- Any issues with the brand rollout\n- Ideas for phase 2\n\nHappy to hop on a quick call this week if helpful.\n\nBest,\nIshan',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    status: 'pending_review'
  }
];

// Initialize with samples
artifacts = [...SAMPLE_ARTIFACTS];

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Content-Type', 'application/json');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  const agentId = req.query?.agentId;

  // GET - List artifacts
  if (req.method === 'GET') {
    let filtered = artifacts;
    
    if (agentId) {
      filtered = artifacts.filter(a => a.agentId === agentId);
    }
    
    // Sort by date, newest first
    filtered.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    
    return res.status(200).json({
      total: filtered.length,
      artifacts: filtered,
      timestamp: new Date().toISOString()
    });
  }
  
  // POST - Create artifact
  if (req.method === 'POST') {
    const { agentId, type, title, summary, content } = req.body || {};
    
    if (!agentId || !type || !title) {
      return res.status(400).json({ error: 'Missing required fields: agentId, type, title' });
    }
    
    const newArtifact = {
      id: `art_${Date.now()}`,
      agentId,
      type,
      title,
      summary: summary || '',
      content: content || '',
      createdAt: new Date().toISOString(),
      status: 'draft'
    };
    
    artifacts.unshift(newArtifact);
    
    return res.status(200).json({
      success: true,
      artifact: newArtifact,
      timestamp: new Date().toISOString()
    });
  }
  
  return res.status(405).json({ error: 'Method not allowed' });
};

// Export for other modules
module.exports.artifacts = artifacts;
